version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspaces/${COMPOSE_PROJECT_NAME:-app}:cached
    command: sleep infinity
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  mailcatcher:
    image: sj26/mailcatcher
    restart: always
    ports:
      - "1080:1080" # Web UI
      - "1025:1025" # SMTP Port

  db_admin:
    image: adminer # Cliente leve para acessar o banco via browser
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  redis_data:
